test_app:
  script:
    - pip install -r requirements.txt
    - cd customer
    - python manage.py migrate
    - python manage.py makemigrations
    - "1"
    - python manage.py test
    - echo test!
