# Generated by Django 3.0.3 on 2021-01-20 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concession',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Operator'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Operator'),
        ),
        migrations.AlterField(
            model_name='usage',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Operator'),
        ),
    ]
