# Generated by Django 3.0.3 on 2021-02-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_connectedaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connectedaccount',
            name='api_url',
        ),
        migrations.AddField(
            model_name='connectedaccount',
            name='operator_id',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='connectedaccount',
            name='auth_url',
            field=models.URLField(default=None),
        ),
    ]
